export { default as OutlinedInput } from '@material-ui/core/OutlinedInput'
export { default as InputLabel } from '@material-ui/core/InputLabel'
export { default as InputAdornment } from '@material-ui/core/InputAdornment'
export { default as FormControl } from '@material-ui/core/FormControl'
export { default as TextField } from '@material-ui/core/TextField'
